name: CI Pipeline

on:
  push:
    branches: [main, tests_branch]
  pull_request:
    branches: [main, tests_branch]

jobs:
  build:
    name: Build, Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install build essentials
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install CLIP library and testing tools
        run: |
          pip install git+https://github.com/openai/CLIP.git
          pip install pytest pytest-cov

      - name: Install project dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --maxfail=1 --disable-warnings --cov=image_recommender \
                 --cov-report=term-missing --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml